default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: postgres
  password:

development:
  <<: *default
  database: walmart_review_development

test:
  <<: *default
  database: walmart_review_test

production:
  <<: *default
  database: walmart_review_production
